name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
